name = "memeho"
main = "src/index.js"
compatibility_date = "2022-12-01"
account_id = "681a0459b3c65398d73979cf1fa918cc"
kv_namespaces = [
  { binding = "TK_DATA", id = "3e85f94b1d094184bf7d113515f41097" },
]

[vars]
DISCORD_PUBLIC_KEY = "cd677acec866ef0eb5879773bdcb9bb4c27f283fb96d1d97428c733bf4545929"
tarkov_current_wipe = "2022-12-28"
tarkov_channel_id = "706856018969231361"
tarkov_role_id = "796051280451338241"
